export const departments = [
  "Engineering",
  "Design",
  "HR",
  "Sales",
  "Product",
  "Quality Assurance",
  "Analytics",
  "IT",
  "Marketing",
  "Finance",
];

export const dummyTrainings = [
  {
    id: 1,
    title: "Workplace Safety",
    department: "Engineering",
    deadline: "2025-08-01",
  },
  {
    id: 2,
    title: "Diversity Training",
    department: "HR",
    deadline: "2025-07-20",
  },
  {
    id: 3,
    title: "Design Principles",
    department: "Design",
    deadline: "2025-07-25",
  },
  {
    id: 4,
    title: "Product Strategy",
    department: "Product",
    deadline: "2025-08-05",
  },
  {
    id: 5,
    title: "QA Automation",
    department: "Quality Assurance",
    deadline: "2025-07-30",
  },
  {
    id: 6,
    title: "Data Ethics",
    department: "Analytics",
    deadline: "2025-08-10",
  },
  {
    id: 7,
    title: "IT Security Protocols",
    department: "IT",
    deadline: "2025-07-28",
  },
  {
    id: 8,
    title: "Marketing Compliance",
    department: "Marketing",
    deadline: "2025-08-15",
  },
  {
    id: 9,
    title: "Financial Regulations",
    department: "Finance",
    deadline: "2025-08-03",
  },
  {
    id: 10,
    title: "HR Conflict Resolution",
    department: "HR",
    deadline: "2025-08-07",
  },
  {
    id: 11,
    title: "Sales Techniques",
    department: "Sales",
    deadline: "2025-08-20",
  },
];

export const dummyEmployees = [
  {
    id: 1,
    name: "Alice Johnson",
    role: "Software Engineer",
    department: "Engineering",
    payRate: 50,
    payFrequency: "Monthly",
    payPeriod: { start: "2025-07-01", end: "2025-07-31" },
    regularHours: 160,
    overtimeHours: 10,
    bonuses: 500,
    deductions: {
      tax: 800,
      insurance: 200,
      retirement: 300,
    },
    performance: {
      rating: 4.5,
      lastReviewDate: "2025-06-15",
      comments: "Consistently delivers high-quality code and meets deadlines.",
      goalsMet: 5,
      goalsTotal: 6,
    },
    email: "alice.johnson@example.com",
    phone: "+1 (555) 123-4567",
    trainings: ["Workplace Safety", "Diversity Training"],
    leaveEntitlement: 20,
    leaveTaken: 7,
    leaveRequests: [
      {
        id: 201,
        type: "Annual",
        startDate: "2025-05-01",
        endDate: "2025-05-05",
        status: "Approved",
      },
      {
        id: 202,
        type: "Sick",
        startDate: "2025-06-10",
        endDate: "2025-06-12",
        status: "Approved",
      }
    ],
  },
  {
    id: 2,
    name: "Bob Smith",
    role: "UI/UX Designer",
    department: "Design",
    payRate: 45,
    payFrequency: "Monthly",
    payPeriod: { start: "2025-07-01", end: "2025-07-31" },
    regularHours: 160,
    overtimeHours: 5,
    bonuses: 300,
    deductions: {
      tax: 700,
      insurance: 180,
      retirement: 250,
    },
    performance: {
      rating: 4.0,
      lastReviewDate: "2025-06-10",
      comments: "Creative designs and good collaboration with developers.",
      goalsMet: 4,
      goalsTotal: 5,
    },
    email: "bob.smith@example.com",
    phone: "+1 (555) 234-5678",
    trainings: ["Workplace Safety"],
    leaveEntitlement: 20,
    leaveTaken: 9,
    leaveRequests: [
      {
        id: 203,
        type: "Annual",
        startDate: "2025-04-15",
        endDate: "2025-04-20",
        status: "Approved",
      }
    ],
  },
  {
    id: 3,
    name: "Carol Lee",
    role: "Product Manager",
    department: "Product",
    payRate: 60,
    payFrequency: "Monthly",
    payPeriod: { start: "2025-07-01", end: "2025-07-31" },
    regularHours: 160,
    overtimeHours: 8,
    bonuses: 700,
    deductions: {
      tax: 1000,
      insurance: 220,
      retirement: 350,
    },
    performance: {
      rating: 4.7,
      lastReviewDate: "2025-06-18",
      comments: "Strong leadership and clear product vision.",
      goalsMet: 6,
      goalsTotal: 6,
    },
    email: "carol.lee@example.com",
    phone: "+1 (555) 345-6789",
    trainings: [],
    leaveEntitlement: 20,
    leaveTaken: 5,
    leaveRequests: [
      {
        id: 204,
        type: "Sick",
        startDate: "2025-03-10",
        endDate: "2025-03-12",
        status: "Approved",
      }
    ],
  },
  {
    id: 4,
    name: "David Kim",
    role: "QA Analyst",
    department: "Quality Assurance",
    payRate: 40,
    payFrequency: "Monthly",
    payPeriod: { start: "2025-07-01", end: "2025-07-31" },
    regularHours: 160,
    overtimeHours: 12,
    bonuses: 200,
    deductions: {
      tax: 600,
      insurance: 150,
      retirement: 200,
    },
    performance: {
      rating: 3.9,
      lastReviewDate: "2025-06-12",
      comments:
        "Met quality standards but needs to improve testing automation.",
      goalsMet: 4,
      goalsTotal: 6,
    },
    email: "david.kim@example.com",
    phone: "+1 (555) 456-7890",
    trainings: ["Workplace Safety", "Testing Automation Basics"],
    leaveEntitlement: 20,
    leaveTaken: 8,
    leaveRequests: [
      {
        id: 101,
        type: "Annual",
        startDate: "2025-06-10",
        endDate: "2025-06-15",
        status: "Approved",
      },
      {
        id: 102,
        type: "Sick",
        startDate: "2025-07-05",
        endDate: "2025-07-07",
        status: "Pending",
      }
    ],
  },
  {
    id: 5,
    name: "Eva Martinez",
    role: "HR Specialist",
    department: "Human Resources",
    payRate: 42,
    payFrequency: "Monthly",
    payPeriod: { start: "2025-07-01", end: "2025-07-31" },
    regularHours: 160,
    overtimeHours: 6,
    bonuses: 250,
    deductions: {
      tax: 650,
      insurance: 170,
      retirement: 230,
    },
    performance: {
      rating: 4.2,
      lastReviewDate: "2025-06-16",
      comments: "Efficient in handling HR queries and onboarding processes.",
      goalsMet: 5,
      goalsTotal: 6,
    },
    email: "eva.martinez@example.com",
    phone: "+1 (555) 567-8901",
    trainings: ["Diversity Training", "Onboarding Procedures"],
    leaveEntitlement: 20,
    leaveTaken: 10,
    leaveRequests: [
      {
        id: 205,
        type: "Annual",
        startDate: "2025-01-20",
        endDate: "2025-01-25",
        status: "Approved",
      },
      {
        id: 206,
        type: "Sick",
        startDate: "2025-02-15",
        endDate: "2025-02-17",
        status: "Approved",
      }
    ],
  },
  {
    id: 6,
    name: "Frank Turner",
    role: "DevOps Engineer",
    department: "Engineering",
    payRate: 55,
    payFrequency: "Monthly",
    payPeriod: { start: "2025-07-01", end: "2025-07-31" },
    regularHours: 160,
    overtimeHours: 7,
    bonuses: 450,
    deductions: {
      tax: 850,
      insurance: 210,
      retirement: 300,
    },
    performance: {
      rating: 4.3,
      lastReviewDate: "2025-06-20",
      comments:
        "Maintains system uptime effectively and manages infrastructure well.",
      goalsMet: 5,
      goalsTotal: 6,
    },
    email: "frank.turner@example.com",
    phone: "+1 (555) 678-9012",
    trainings: ["Workplace Safety", "Infrastructure Management"],
    leaveEntitlement: 20,
    leaveTaken: 6,
    leaveRequests: [
      {
        id: 207,
        type: "Annual",
        startDate: "2025-03-05",
        endDate: "2025-03-10",
        status: "Approved",
      }
    ],
  },
  {
    id: 7,
    name: "Grace Hopper",
    role: "Data Scientist",
    department: "Analytics",
    payRate: 65,
    payFrequency: "Monthly",
    payPeriod: { start: "2025-07-01", end: "2025-07-31" },
    regularHours: 160,
    overtimeHours: 4,
    bonuses: 600,
    deductions: {
      tax: 950,
      insurance: 230,
      retirement: 350,
    },
    performance: {
      rating: 4.8,
      lastReviewDate: "2025-06-22",
      comments:
        "Delivers data-driven insights that support key business decisions.",
      goalsMet: 6,
      goalsTotal: 6,
    },
    email: "grace.hopper@example.com",
    phone: "+1 (555) 789-0123",
    trainings: ["Data Analysis", "Workplace Safety"],
    leaveEntitlement: 20,
    leaveTaken: 11,
    leaveRequests: [
      {
        id: 208,
        type: "Sick",
        startDate: "2025-04-01",
        endDate: "2025-04-03",
        status: "Approved",
      },
      {
        id: 209,
        type: "Annual",
        startDate: "2025-05-10",
        endDate: "2025-05-15",
        status: "Approved",
      }
    ],
  },
  {
    id: 8,
    name: "Henry Adams",
    role: "IT Support Specialist",
    department: "IT",
    payRate: 38,
    payFrequency: "Monthly",
    payPeriod: { start: "2025-07-01", end: "2025-07-31" },
    regularHours: 160,
    overtimeHours: 9,
    bonuses: 220,
    deductions: {
      tax: 550,
      insurance: 140,
      retirement: 190,
    },
    performance: {
      rating: 3.8,
      lastReviewDate: "2025-06-19",
      comments:
        "Provides prompt support but needs to improve ticket resolution time.",
      goalsMet: 4,
      goalsTotal: 6,
    },
    email: "henry.adams@example.com",
    phone: "+1 (555) 890-1234",
    trainings: ["Customer Service", "Workplace Safety"],
    leaveEntitlement: 20,
    leaveTaken: 4,
    leaveRequests: [
      {
        id: 210,
        type: "Annual",
        startDate: "2025-02-20",
        endDate: "2025-02-22",
        status: "Approved",
      }
    ],
  },
  {
    id: 9,
    name: "Isabella Clarke",
    role: "Marketing Specialist",
    department: "Marketing",
    payRate: 48,
    payFrequency: "Monthly",
    payPeriod: { start: "2025-07-01", end: "2025-07-31" },
    regularHours: 160,
    overtimeHours: 6,
    bonuses: 300,
    deductions: {
      tax: 720,
      insurance: 180,
      retirement: 220,
    },
    performance: {
      rating: 4.1,
      lastReviewDate: "2025-06-14",
      comments:
        "Creates effective campaigns and collaborates well with the team.",
      goalsMet: 5,
      goalsTotal: 6,
    },
    email: "isabella.clarke@example.com",
    phone: "+1 (555) 901-2345",
    trainings: ["Marketing Strategies", "Workplace Safety"],
    leaveEntitlement: 20,
    leaveTaken: 12,
    leaveRequests: [
      {
        id: 211,
        type: "Annual",
        startDate: "2025-01-05",
        endDate: "2025-01-10",
        status: "Pending",
      },
      {
        id: 212,
        type: "Sick",
        startDate: "2025-03-12",
        endDate: "2025-03-14",
        status: "Pending",
      }
    ],
  },
  {
    id: 10,
    name: "Jack Nolan",
    role: "Finance Analyst",
    department: "Finance",
    payRate: 58,
    payFrequency: "Monthly",
    payPeriod: { start: "2025-07-01", end: "2025-07-31" },
    regularHours: 160,
    overtimeHours: 3,
    bonuses: 400,
    deductions: {
      tax: 870,
      insurance: 200,
      retirement: 310,
    },
    performance: {
      rating: 4.4,
      lastReviewDate: "2025-06-17",
      comments: "Highly analytical and dependable in financial reporting.",
      goalsMet: 5,
      goalsTotal: 6,
    },
    email: "jack.nolan@example.com",
    phone: "+1 (555) 012-3456",
    trainings: ["Financial Compliance", "Workplace Safety"],
    leaveEntitlement: 20,
    leaveTaken: 8,
    leaveRequests: [
      {
        id: 213,
        type: "Annual",
        startDate: "2025-04-25",
        endDate: "2025-04-30",
        status: "Approved",
      }
    ],
  },
];

export default dummyEmployees;
